import { GlobalConfiguration } from "../../cfg"
import { QuartzPluginData } from "../vfile"
import { QuartzEmitterPlugin } from "../types"
import { BuildCtx } from "../../util/ctx"
import { FullSlug, joinSegments, simplifySlug } from "../../util/path"
import { escapeHTML, getDate, byDateAndAlphabetical } from "@quartz-community/utils"
import { write } from "./helpers"

export interface Options {
  rssSlug: string
  rssLimit?: number
  rssRecentPostsText: string
  rssLastFewPostsText: (count: number) => string
}

const defaultOptions: Options = {
  rssSlug: "index",
  rssLimit: 10,
  rssRecentPostsText: "Recent posts",
  rssLastFewPostsText: (count) => `Last ${count} posts`,
}

function createRSSItem(
  cfg: GlobalConfiguration,
  data: QuartzPluginData & { slug: FullSlug },
): string {
  const base = cfg.baseUrl ?? ""
  const url = `https://${joinSegments(base, encodeURI(simplifySlug(data.slug)))}`
  return `<item>
    <title>${escapeHTML(data.frontmatter?.title ?? "")}</title>
    <link>${url}</link>
    <guid>${url}</guid>
    <description><![CDATA[ ${data.description ?? ""} ]]></description>
    <pubDate>${getDate(data)?.toUTCString()}</pubDate>
  </item>`
}

/**
 * Builds the RSS feed from real content only. Virtual pages generated by
 * PageTypeDispatcher (tag pages, folder pages, the tag index) never carry a
 * `date`, so upstream ContentIndex's feed generator falls back to "now" for
 * them, which sorts them ahead of every dated Post. Excluding them by slug
 * here keeps them out of the feed entirely while leaving search, sitemap,
 * and Explorer (all driven by ContentIndex, which still sees them) unaffected.
 * See issue #5.
 */
export function generateRSSFeed(
  cfg: GlobalConfiguration,
  content: [unknown, { data: QuartzPluginData }][],
  virtualPageSlugs: ReadonlySet<FullSlug>,
  options: Options,
): string {
  const pageTitle = cfg.pageTitle ?? ""

  const entries = content
    .map(([, file]) => file.data)
    .filter((data): data is QuartzPluginData & { slug: FullSlug } => data.slug !== undefined)
    .filter((data) => !virtualPageSlugs.has(data.slug))
    .filter((data) => data.unlisted !== true)
    .sort(byDateAndAlphabetical())

  const limit = options.rssLimit
  const limited = entries.slice(0, limit ?? entries.length)
  const items = limited.map((data) => createRSSItem(cfg, data)).join("")
  const description = `${limit ? options.rssLastFewPostsText(limit) : options.rssRecentPostsText} on ${escapeHTML(pageTitle)}`

  return `<?xml version="1.0" encoding="UTF-8" ?>
<rss version="2.0">
    <channel>
      <title>${escapeHTML(pageTitle)}</title>
      <link>https://${joinSegments(cfg.baseUrl ?? "")}</link>
      <description>${description}</description>
      <generator>Quartz -- quartz.jzhao.xyz</generator>
      ${items}
    </channel>
  </rss>`
}

export const Rss: QuartzEmitterPlugin<Partial<Options>> = (userOpts) => {
  const options: Options = { ...defaultOptions, ...userOpts }

  const emitAll = async (ctx: BuildCtx, content: [unknown, { data: QuartzPluginData }][]) => {
    const virtualPageSlugs = new Set(
      ctx.virtualPages
        .map(([, vfile]) => vfile.data.slug)
        .filter((slug): slug is FullSlug => slug !== undefined),
    )
    const feed = generateRSSFeed(ctx.cfg.configuration, content, virtualPageSlugs, options)
    const fp = await write({ ctx, content: feed, slug: options.rssSlug as FullSlug, ext: ".xml" })
    return [fp]
  }

  return {
    name: "Rss",
    emit: (ctx, content) => emitAll(ctx, content),
    partialEmit: (ctx, content) => emitAll(ctx, content),
  }
}
